name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore API dependencies
      working-directory: API
      run: dotnet restore
    - name: Build API
      working-directory: API
      run: dotnet build --no-restore

    - name: Restore SPA dependencies
      working-directory: weather-app
      run: npm install
    - name: Build
      working-directory: weather-app
      run: CI=false npm run ng build -- --configuration=production
